### ISSUE TITLE
Allow ignoring more than the the .git folders

### ISSUE THREAD

**Issue by StanleySweet** [0ad-matters/gh-action-build-pyromod#6]
A few mods like the mods adding the source files on git or @rossenburgg 's mod include folders that shouldn't be packaged. currently only .git is ignored.

**Comment by andy5995** [comment]
@StanleySweet Technically, removing files or directories was already allowed. After the action runs, the pyromod can be changed before the workflow ends by manually adding in commands like `zip -d...`. But still, adding the arg makes it a little easier I think for end-users. Thanks for the suggestions.
